import Head from "next/head";
import { HomePage } from "../Components/HomePage/HomePage";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className="container-fluid center">
      <Head>
        <title>dev-decentralized-shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomePage></HomePage>
      </main>
    </div>
  );
}
