import Head from "next/head";

import { LandingPage } from "../Components/LandingPage/LandingPage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="center">
      <Head>
        <title>dev-decentralized-shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/@primer/css@^18.0.0/dist/primer.css"
        />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>

      <main className={styles.main}>
        <LandingPage></LandingPage>
      </main>
    </div>
  );
}
