import Head from "next/head";
import { HomePage } from "../Components/HomePage/HomePage";

export default function App() {
  return (
    <div>
      <Head>
        <title>Kkdev-decentralized-shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage></HomePage>
      </main>
    </div>
  );
}
